<x-layouts.app>
    <x-carousel/>
    <livewire:about-school/>
    <x-valores-card/>
    <x-noticias-destacadas/>
    <x-alianzas/>
    <x-latest-gallery-images/>
    <x-faq/>
    <x-testimonials/>
    <livewire-contact-form/>
</x-layouts.app>
